services:
  dpsrv-n8n:
    container_name: dpsrv-n8n-${tag:-latest}
    image: n8nio/n8n:latest
    ports:
      - 5678:5678
    env_file:
      - ${DPSRV_HOME}/rc/secrets/n8n/n8n.env
      - ${DPSRV_HOME}/rc/secrets/local/${HOSTNAME}/${HOSTNAME}.env
    volumes:
      - ${DPSRV_HOME}/rc/secrets/n8n/config:/home/node/.n8n/config
      - ${DPSRV_NODE_HOME}/srv/n8n/database.sqlite:/home/node/.n8n/database.sqlite
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
